### ISSUE TITLE
package functions cannot be called without attaching the package

### ISSUE THREAD

**Issue by rubenarslan** [bnowok/synthpop#2]
Don't know if this would be too much work and don't really mind, but I think packages are supposed to work when called like this too.

``` r
synthpop::syn(iris)
#> Error in check.method.syn(setup, data, proper): The following functions were not found: syn.sample, syn.cart, syn.cart, syn.cart, syn.cart
```

**Comment by bnowok** [comment]
Checks on the availability of synthesis methods is conducted differently and the package can be used now without attaching it.
