### ISSUE TITLE
No results show when using compare function

### ISSUE THREAD

**Issue by 477539sl** [bnowok/synthpop#21]
Hi there. 

First of all, I am using some code references from this blog for my own code: https://www.r-bloggers.com/2019/01/generating-synthetic-data-sets-with-synthpop-in-r/ 

I used the code from the blog (shared above) as a way for me to identify the underlying problems between my own code and the reference code. 

The current issue is that I cannot create plots when I compare my synthetic data frame (in this case called dataframe A) to my original dataframe (dataframe B). The types of the variables can be seen below: 
A:
![A](https://user-images.githubusercontent.com/103747790/168679846-146d2fd6-c540-4492-a9f5-23d5950c5639.PNG)

B:
![B](https://user-images.githubusercontent.com/103747790/168679880-14f6467e-69f5-4f38-b83c-0981c4bfda21.PNG)

This is the type of plot I wish to obtain to check the distribution between both dataframes:
![Plot](https://user-images.githubusercontent.com/103747790/168680014-82d7fa66-b46e-48ee-ac9e-245b093825fc.jpeg)

Somehow I cannot replicate the same results from the blog although I have a similar dataframe as the blog when it comes down to the types of variables used. As I dig deeper into the issue, one thing I notice is that when I run the following compare function using data from the blog, the details of the object list I get from using the referenced data are different than my data. 

Reference data object list: 
![D](https://user-images.githubusercontent.com/103747790/168681719-eaf796fd-98c1-4c08-90b7-be389323ba1d.jpeg)

My data object list:
![C](https://user-images.githubusercontent.com/103747790/168681771-6d86350d-3bb5-422b-ac09-7382b8a45894.png)

I am not sure how to solve this problem although this is the closest error I can track to why the compare function is not working for me.

**Comment by LotteVanUtrecht** [comment]
Hello,

It seems that dataframe A contains character values, where dataframe B contains factors. Have you tried factorizing the character vectors before synthesizing? This has worked for me in the past.

Best,
Lotte Pater

**Comment by 477539sl** [comment]
Hello, 

I figured out the problem of why the compare function didn't work. Apparently it's because my original dataframe is not stored as a dataframe, but rather it is stored as a table. Hence that is why it didn't work. Hope this realization will be helpful to any coders in the future, cheers!
