### ISSUE TITLE
problems in syn.strata specifying the name of the stratum variable as a character string

### ISSUE THREAD

**Issue by rubenarslan** [bnowok/synthpop#3]
When I specify a stratum variable as a character string, the stratum variable still causes an error down the line due to exceeeding the maximum number of factor levels. 
When I specify it as a numeric (so it's not part of the dataset), it works. Presumably, synthpop should remove it from the dataset first.

**Comment by bnowok** [comment]
Check on maximum number of factor levels is not applied to stratification variable(s) anymore.
